[package]
name = "matlas"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
humfmt = "0.7.0"
uuid = "1.26.1"
rand = { version = "0.10.3", features = ["serde"] }
scc = { version = "3.8.8", features = ["serde"] }
blake3 = "1.8.7"
postcard = "1.1.3"
